### ISSUE TITLE
helm search repo dex gives No results found

### ISSUE THREAD

**Issue by AmandeepBhupal** [dexidp/helm-charts#1]
Hi, I tried the two commands given in the readme doc, the results I got are:
**_helm repo add dex https://charts.dexidp.io_**
"dex" has been added to your repositories

**_helm search repo dex_**
No results found

What could I be doing wrong? Or is this repo not ready yet?

**Comment by carpenike** [comment]
Heh, was looking at this today myself. :)

Looks like they don't have any charts yet...

https://github.com/dexidp/dex/issues/1709#issuecomment-746822918

**Comment by carpenike** [comment]
@sagikazarmark -- are you interested in a PR for a dex chart to start with? Any chance you have an early on dev version?

**Comment by sagikazarmark** [comment]
I do have something locally, but haven't finished it yet. Configuration doesn't make things easy. I'll try to push something soon.

**Comment by asetty** [comment]
@sagikazarmark happy to see some conversation around this. 
Just curious, is the chart you're working with locally derived from the one from the old stable repo? https://github.com/helm/charts/tree/master/stable/dex

**Comment by sagikazarmark** [comment]
Nope, it's brand new. The one in the old stable (that we forked at Banzai Cloud) is in pretty bad shape I'd say.

**Comment by sagikazarmark** [comment]
Let's track this in #2
