### ISSUE TITLE
podAnnotations are not working

### ISSUE THREAD

**Issue by jengo** [dexidp/helm-charts#17]
I am trying to deploy this chart using the Hashicorp vault operator which requires the use of annotations.  However, no matter which values I set I get the following error.  Setting this map in a values file and CLI both trigger the exact same error.  Even setting with something like podAnnotations.a=b throws the same error.

Helm version 3.5.2
```
helm template dex/dex --set podAnnotations.vault.security.banzaicloud.io/vault-addr="https://vault.vault:8200"
```

> Error: template: dex/templates/deployment.yaml:19:28: executing "dex/templates/deployment.yaml" at <include (print $.Template.BasePath "/secret.yaml") .>: error calling include: template: dex/templates/secret.yaml:4:11: executing "dex/templates/secret.yaml" at <include "dex.componentname" (list . "config")>: error calling include: template: dex/templates/_helpers.tpl:74:20: executing "dex.componentname" at <include "dex.fullname" $global>: error calling include: template: dex/templates/_helpers.tpl:14:14: executing "dex.fullname" at <.Values.fullnameOverride>: nil pointer evaluating interface {}.fullnameOverride

```
helm template dex/dex --set podAnnotations.a=b
```

> Error: template: dex/templates/deployment.yaml:19:28: executing "dex/templates/deployment.yaml" at <include (print $.Template.BasePath "/secret.yaml") .>: error calling include: template: dex/templates/secret.yaml:4:11: executing "dex/templates/secret.yaml" at <include "dex.componentname" (list . "config")>: error calling include: template: dex/templates/_helpers.tpl:74:20: executing "dex.componentname" at <include "dex.fullname" $global>: error calling include: template: dex/templates/_helpers.tpl:14:14: executing "dex.fullname" at <.Values.fullnameOverride>: nil pointer evaluating interface {}.fullnameOverride

**Comment by sagikazarmark** [comment]
Thanks for reporting, should be fixed now.
