### ISSUE TITLE
Dex release to pin image to a stable version

### ISSUE THREAD

**Issue by Diaoul** [dexidp/helm-charts#19]
Currently the image used is "master" which is problematic and last tagged version of dex doesn't work with this chart. Is it possible to use a tag that works with the helm chart and is not master? Or make an official release of dex with support for this chart?

Relevant code: https://github.com/dexidp/helm-charts/blob/master/charts/dex/values.yaml#L13-L15

**Comment by nabokihms** [comment]
The first stable version of dex for this chart will be v2.28.0. We are [almost ready](https://github.com/dexidp/dex/milestone/20) to release it.

**Comment by sagikazarmark** [comment]
As the linked code points out, there is no such release yet, v2.28.0 will be the first stable version supported by the helm chart.

In addition, the helm chart is not considered to be stable yet either.

0.1.0 will be released with  stable dex tag.
