### ISSUE TITLE
.Values.service.port not documented/undefined

### ISSUE THREAD

**Issue by lwj5** [dexidp/helm-charts#27]
This is not documented

https://github.com/dexidp/helm-charts/blob/e07a4ace80ee8f60011859b2b4880258ff71b1d6/charts/dex/templates/ingress.yaml#L3

Either document it or revert to 

https://github.com/dexidp/helm-charts/blob/74bce57289cd80ecfd7d1a0cb12df0637ed44cba/charts/dex/templates/ingress.yaml#L3

**Comment by ruzickap** [comment]
Looks like the Ingress part of helm chart is broken due to last changes...

**Comment by sagikazarmark** [comment]
@lwj5 @ruzickap Should be fixed now.
