### ISSUE TITLE
Changelog

### ISSUE THREAD

**Issue by Raboo** [dexidp/helm-charts#31]
Hi,

It would be nice if there was a Changelog.
@sagikazarmark could you perhaps keep a Changelog? You're already writing into the chart the latest changes. But since the chart only displays the changes for the latest release, you have to dig through git history to see all the changes if you haven't upgraded in a few releases.

**Comment by sagikazarmark** [comment]
@Raboo you can see a change log here: https://artifacthub.io/packages/helm/dex/dex?modal=changelog

Would that work for now?

**Comment by Raboo** [comment]
Ah, yes, sorry didn't even know that it was published on artifact hub
