### ISSUE TITLE
Cannot Define Secret Environment Variables

### ISSUE THREAD

**Issue by cpumanaz** [dexidp/helm-charts#53]
The helm chart allows environment to be configured, but env: does not  complete `env:` section.

https://kubernetes.io/docs/concepts/configuration/secret/#using-secrets-as-environment-variables

`env:` section should work the same as you define `envFrom:`  The range logic assumes the end user only ever wants to use `value:` but Kubernetes allows more things than `value:`  Please update the helm chart to replace the range with  `with.Values.env` with an nindent. Then the user can define the environment according to what Kubernetes allows.

```          env:
            {{- range $key, $value := .Values.env }}
            - name: {{ $key }}
              value: {{ $value | quote }}
            {{- end }}
          {{- with .Values.envFrom }}
          envFrom:
            {{- toYaml . | nindent 12 }}
          {{- end }}
```

**Comment by sagikazarmark** [comment]
This came up in a different case here: https://github.com/sagikazarmark/helm-charts/pull/92

Unfortunately, env is already used. Would the above solution work for you?

**Comment by jeanlouhallee** [comment]
@sagikazarmark Would you allow me to do a PR for this? Solution yon pointed out here sagikazarmark/helm-charts#92 would work for me.

**Comment by sagikazarmark** [comment]
@jeanlouhallee yes, feel free to submit a PR. FYI we have a new contributing guide that should help you make all the necessary changes. Thanks!
